name: Build and Deploy java 
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code test
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.9
    - name: Build with Maven
      env:
        ART_USER: ${{ secrets.ART_USER }}
        ART_PASS: ${{ secrets.ART_PASS }}
      run: mvn clean test package deploy -s .mvn/settings.xml

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: hello-world-jar
        path: target/hello-world-1.0.0-SNAPSHOT.jar

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip docker]') }}
    env:
      ART_URL: reg.mevijay.dev
      REPO: demo
      AWS_REGION : "eu-north-1"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: hello-world-jar
        path: ./target/
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        role-to-assume: arn:aws:iam::430118834478:role/gh-action-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: reg.mevijay.dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker images
        docker build -t $ART_URL/$REPO/hello-world:latest .
        docker push $ART_URL/$REPO/hello-world:latest
